[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "build/web"
  command = "flutter build web --release --dart-define=API_BASE_URL=https://api-v2.zendfi.tech"

[[headers]]
  for = "/flutter_bootstrap.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
